version: '3'
services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    command: '--init-file /data/application/init.sql'
    volumes:
      - './init.sql:/data/application/init.sql'
      - './data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=pwd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    links:
      - mysql:db

  login:
    build:
      context: ./services/login
      dockerfile: Dockerfile
    ports:
      - 8003:8003
    environment:
      - NODE_ENV=dev
    restart: always

volumes:
  mysql_data: