version: '3'
services:
  login_service:
    container_name: login_service
    build:
      context: ./services/login
      dockerfile: Dockerfile
    image: login-service-image
    ports:
      - 0:8003
    environment:
      - NODE_ENV=prod
    restart: always
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-image
    depends_on:
      - login_service
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ec2-user/logs/nginx:/var/log/nginx
