name: Unit Test

on:
  pull_request:
    branches: ["main"]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test Login Service
        working-directory: ./services/login
        run: |
          npm install
          npm test
