name: Deploy to ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: ${{ secrets.ECR_REPO }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set essential login AWS details to configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create production env file
        run: |
          cd ${{ github.workspace }}
          # Create production environment files
          echo "ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" > services/login/.env
          echo "SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> services/login/.env
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> services/login/.env
      
      - name: Create nginx.conf file
        env: 
          EC2_PUBLIC_HOST_NAME: ${{ secrets.EC2_PUBLIC_HOST_NAME }}
        run: |
          cd ./nginx
          envsubst '${EC2_PUBLIC_HOST_NAME}' < nginx.template.conf > nginx.conf

      - name: Build and tag the Docker images
        run: |
          docker-compose build
          docker images
          cat services/login/.env
          
      - name: Login in ECS
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Tag Docker image
        run: |
          docker tag login_service_image ${{ env.ECR_REPOSITORY }}/transition_website:login_service_image_${{ github.sha }}

      - name: Push Docker image to ECR Public
        run: |
          docker push ${{ env.ECR_REPOSITORY }}/transition_website:login_service_image_${{ github.sha }}

      # - name: Login in ECS
      #   run: |
      #     aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      # - name: Tag Docker image
      #   run: |
      #     docker tag transition_website_login ${{ env.ECR_REPOSITORY }}/transition_website:$(date +%s)

      # - name: Push Docker image to ECR Public
      #   run: |
      #     docker push ${{ env.ECR_REPOSITORY }}/transition_website:$(date +%s)
